name: Pull Request Build

on:
  pull_request

jobs:
  
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      shell: cmd
      run: build_windows.bat
      
    - name: Package
      uses: actions/upload-artifact@v4
      with:
        name: mini_video_windows
        path: |
          mini_video_dx11.exe
          mini_video_dx12.exe
          mini_video_vulkan.exe
          yuv_to_rgbCS.hlsl
          test.mp4
          dxcompiler.dll
          dxil.dll
          d3dcompiler_47.dll

          
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        sudo apt update
        sudo apt install libx11-dev
        g++ -o mini_video_vulkan.exe mini_video_vulkan.cpp -O3 -lX11

    - name: Package
      uses: actions/upload-artifact@v4
      with:
        name: mini_video_linux
        path: |
          mini_video_vulkan.exe
          libdxcompiler.so
          yuv_to_rgbCS.hlsl
          test.mp4
